
CREATE TABLE CAR_COMPANY 
(
  CRC_COMPANY_ID    NUMBER(7) NOT NULL,
  CRC_NAME          VARCHAR2(30) NOT NULL,
  CREATED_BY        VARCHAR2(16 CHAR) NOT NULL,
  CREATED_TS        TIMESTAMP(6) NOT NULL,
  MODIFIED_BY       VARCHAR2(16 CHAR),
  MODIFIED_TS       TIMESTAMP(6),
  VERSION			NUMBER(18) NOT NULL
);

ALTER TABLE CAR_COMPANY ADD CONSTRAINT PK_CRC_COMPANY_ID PRIMARY KEY (CRC_COMPANY_ID);
ALTER TABLE CAR_COMPANY	ADD CONSTRAINT UQ_CRC_NAME UNIQUE (CRC_NAME);

CREATE TABLE CAR_BRAND 
(
  CRB_ID              NUMBER(7) NOT NULL,
  FK_CRC_COMPANY_ID   NUMBER(7) NOT NULL,
  CRB_BRAND_NAME      VARCHAR2(16 CHAR) NOT NULL,
  CRB_INTRO_YEAR      NUMBER(4) NOT NULL,
  CREATED_BY          VARCHAR2(16 CHAR) NOT NULL,
  CREATED_TS          TIMESTAMP(6) NOT NULL,
  MODIFIED_BY         VARCHAR2(16 CHAR),
  MODIFIED_TS         TIMESTAMP(6),
  VERSION			  NUMBER(18) NOT NULL
);

ALTER TABLE CAR_BRAND ADD CONSTRAINT PK_CRB_ID PRIMARY KEY (CRB_ID);
ALTER TABLE CAR_BRAND ADD CONSTRAINT FK_CRB_CRC_COMPANY_ID FOREIGN KEY (FK_CRC_COMPANY_ID) REFERENCES CAR_COMPANY (CRC_COMPANY_ID);
ALTER TABLE CAR_BRAND ADD CONSTRAINT UQ_FK_CRC_COMPANY_ID_CRB_BRAND_NAME UNIQUE (FK_CRC_COMPANY_ID, CRB_BRAND_NAME);

CREATE TABLE COUNTRY 
(
  CNT_ID              NUMBER(7) NOT NULL,
  CNT_NAME            VARCHAR2(30 CHAR) NOT NULL,
  CREATED_BY          VARCHAR2(16 CHAR) NOT NULL,
  CREATED_TS          TIMESTAMP(6) NOT NULL,
  MODIFIED_BY         VARCHAR2(16 CHAR),
  MODIFIED_TS         TIMESTAMP(6),
  VERSION			  NUMBER(18) NOT NULL
);

ALTER TABLE COUNTRY ADD CONSTRAINT PK_CNT_ID PRIMARY KEY (CNT_ID);
ALTER TABLE COUNTRY ADD CONSTRAINT UQ_CNT_NAME UNIQUE (CNT_NAME);


CREATE TABLE COUNTRY_LOCATION
(
   CRL_ID            NUMBER(7) NOT NULL,
   FK_CNT_ID         NUMBER(7) NOT NULL,
   CRL_STREET        VARCHAR2(40 CHAR) NOT NULL,
   CRL_ADDRESS1      VARCHAR2(40 CHAR) NOT NULL,
   CRL_ADDRESS2      VARCHAR2(40 CHAR),
   CRL_STATE         VARCHAR2(20 CHAR) NOT NULL,
   CRL_ZIP           NUMBER(7) NOT NULL,
   CREATED_BY        VARCHAR2(16 CHAR) NOT NULL,
   CREATED_TS        TIMESTAMP(6) NOT NULL,
   MODIFIED_BY       VARCHAR2(16 CHAR),
   MODIFIED_TS       TIMESTAMP(6),
   VERSION			 NUMBER(18) NOT NULL
);
ALTER TABLE COUNTRY_LOCATION ADD CONSTRAINT PK_CRL_ID PRIMARY KEY (CRL_ID);
ALTER TABLE COUNTRY_LOCATION ADD CONSTRAINT FK_CRL_CNT_ID FOREIGN KEY (FK_CNT_ID) REFERENCES COUNTRY (CNT_ID);


CREATE TABLE COUNTRY_CAR_BRAND
(
   FK_CNT_ID         NUMBER(7) NOT NULL,
   FK_CRB_ID         NUMBER(7) NOT NULL,
   FK_CRL_ID         NUMBER(7) NOT NULL,
   CREATED_BY        VARCHAR2(16 CHAR) NOT NULL,
   CREATED_TS        TIMESTAMP(6) NOT NULL,
   MODIFIED_BY       VARCHAR2(16 CHAR),
   MODIFIED_TS       TIMESTAMP(6),
   VERSION			 NUMBER(18) NOT NULL
);
  
ALTER TABLE COUNTRY_CAR_BRAND ADD CONSTRAINT FK_CCB_CNT_ID FOREIGN KEY (FK_CNT_ID) REFERENCES COUNTRY (CNT_ID);
ALTER TABLE COUNTRY_CAR_BRAND ADD CONSTRAINT FK_CCB_CRB_ID FOREIGN KEY (FK_CRB_ID) REFERENCES CAR_BRAND (CRB_ID);
ALTER TABLE COUNTRY_CAR_BRAND ADD CONSTRAINT FK_CCB_CRL_ID FOREIGN KEY (FK_CRL_ID) REFERENCES COUNTRY_LOCATION (CRL_ID);
  

  
 